defaults:
    - default
    - _self_

num_evals: 1000
B: 512
T: 1_000_000_000
T_eval: 2_048_000
ds_path: chess
wandb_project: picodo
wandb_tag: chess
wandb_mode: online

model:
  D: 128
  mlp_expansion: 1
  L: 128
  N: 3
  dtype: null
  V: 64

opt:
  name: adam
  B: 512
  lr: 0.4
  b1: 0.9
  b2: 0.95
  warmup_tokens: 10_000_000
  mup: true
  schedule: linear
